# Generated by Django 2.1.5 on 2019-02-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='ratio',
            new_name='radius',
        ),
    ]
