# Generated by Django 2.1.5 on 2019-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20190214_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='topic',
            field=models.CharField(choices=[('Football', 'Football'), ('Travel', 'Travel'), ('Politics', 'Politics'), ('Art', 'Art'), ('Dating', 'Dating'), ('Music', 'Music'), ('Movies', 'Movies'), ('Series', 'Series'), ('Food', 'Food')], max_length=50),
        ),
    ]
