# Generated by Django 2.1.5 on 2019-02-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20190215_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='radius',
            new_name='radius_in_m',
        ),
    ]
