# Generated by Django 2.1.5 on 2019-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
