# Generated by Django 2.1.7 on 2019-03-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmessage',
            name='match',
        ),
        migrations.AddField(
            model_name='matchmessage',
            name='in_match',
            field=models.ForeignKey(default=159, on_delete=django.db.models.deletion.CASCADE, related_name='in_match', to='targets.Match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchmessage',
            name='sent_by',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
