# Generated by Django 2.1.7 on 2019-03-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190313_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmessage',
            name='in_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='targets.Match'),
        ),
    ]
