# Generated by Django 2.1.7 on 2019-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190313_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmessage',
            name='seen_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
